seed: 3
resume: True
stats_print_interval: 10
validation_epoch_interval: 30
checkpoint_epoch_interval: 30
checkpoint_path: 'checkpoints/lego_pt3d.pth'
data:
  dataset_path: './nerf_synthetic/lego/'
  train_size: 10
  validation_size: 100
  test_size: 200
test:
  mode: 'evaluation'
  trajectory_type: 'circular'
  up: [0.0, 0.0, 1.0]
  scene_center: [0.0, 0.0, 0.0]
  n_frames: 100
  fps: 20
  trajectory_scale: 0.2
optimizer:
  max_epochs: 20000
  lr: 0.0005
  lr_scheduler_step_size: 5000
  lr_scheduler_gamma: 0.1
renderer:
  Nc: 64
  Nf: 128
  min_depth: 2.0
  max_depth: 6.0
  stratified: True
implicit_function:
  n_harmonic_functions_xyz: 10
  n_harmonic_functions_dir: 4
  n_hidden_neurons_xyz: 256
  n_hidden_neurons_dir: 128
  density_noise_std: 0.0
  n_layers_xyz: 8
